# Generated by Django 5.0.2 on 2024-07-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('username', 'account_number')},
        ),
    ]
